spring:
  data:
    mongodb:
#      version: 4.0.21
      database: match-service
#      port: 27017
      uri: mongodb+srv://match-service:$MONGODB_PASSWORD@prod.h0ytr1d.mongodb.net/?retryWrites=true&w=majority
logging:
  level:
    org:
      springframework:
        cloud=DEBUG: